# Generated by Django 6.0 on 2025-12-07 02:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('comments', models.TextField(blank=True, null=True)),
                ('user_account', models.OneToOneField(blank=True, help_text='Optional link to user account if this person has registered', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_orders', to='webapp.person')),
                ('people', models.ManyToManyField(related_name='orders', to='webapp.person')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webapp.pizzavendor')),
            ],
        ),
        migrations.CreateModel(
            name='PersonToppingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(help_text='Preference weight (e.g., positive for likes, negative for dislikes)')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_preferences', to='webapp.person')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_preferences', to='webapp.topping')),
            ],
            options={
                'verbose_name_plural': 'Person Topping Preferences',
                'unique_together': {('person', 'topping')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_toppings',
            field=models.ManyToManyField(related_name='people_with_preference', through='webapp.PersonToppingPreference', to='webapp.topping'),
        ),
        migrations.CreateModel(
            name='OrderedPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('whole', 'Whole'), ('half', 'Half')], default='whole', max_length=5)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='webapp.order')),
                ('people', models.ManyToManyField(related_name='ordered_pizzas', to='webapp.person')),
                ('left_toppings', models.ManyToManyField(blank=True, related_name='pizzas_as_left_topping', to='webapp.topping')),
                ('right_toppings', models.ManyToManyField(blank=True, related_name='pizzas_as_right_topping', to='webapp.topping')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='webapp.topping')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_toppings', to='webapp.pizzavendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Toppings',
                'unique_together': {('vendor', 'topping')},
            },
        ),
        migrations.AddField(
            model_name='pizzavendor',
            name='toppings',
            field=models.ManyToManyField(related_name='vendors_offering', through='webapp.VendorTopping', to='webapp.topping'),
        ),
    ]
