# Generated by Django 6.0.2 on 2026-02-22 15:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_pizzas', models.IntegerField(default=1, help_text='Number of pizzas to order')),
                ('optimization_mode', models.CharField(choices=[('maximize_likes', 'Maximize Likes'), ('minimize_dislikes', 'Minimize Dislikes')], default='maximize_likes', help_text='Which optimization strategy to use', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comments', models.TextField(blank=True, null=True)),
                ('guest_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('unrated_is_dislike', models.BooleanField(default=False, help_text='If True, toppings with no recorded preference are treated as Dislike (-1) during optimization.')),
                ('guest_for_order', models.ForeignKey(blank=True, help_text='Set for guest Persons; null for persistent users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_persons', to='webapp.order')),
                ('user_account', models.OneToOneField(blank=True, help_text='Linked user account (null for guests)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_orders', to='webapp.person'),
        ),
        migrations.AddField(
            model_name='order',
            name='people',
            field=models.ManyToManyField(related_name='orders', to='webapp.person'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='webapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(related_name='pizza_groups', through='webapp.GroupMembership', to='webapp.person')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='webapp.pizzagroup'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='webapp.pizzagroup'),
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='webapp.pizzavendor'),
        ),
        migrations.CreateModel(
            name='PersonToppingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(choices=[(-2, 'Allergy'), (-1, 'Dislike'), (0, 'Neutral'), (1, 'Like')], default=0, help_text='Preference level: ALLERGY (-2) is a hard constraint, DISLIKE (-1) is minimized, NEUTRAL (0), LIKE (1) is maximized')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_preferences', to='webapp.person')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_preferences', to='webapp.topping')),
            ],
            options={
                'verbose_name_plural': 'Person Topping Preferences',
                'unique_together': {('person', 'topping')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_toppings',
            field=models.ManyToManyField(related_name='people_with_preference', through='webapp.PersonToppingPreference', to='webapp.topping'),
        ),
        migrations.CreateModel(
            name='OrderedPizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='webapp.order')),
                ('people', models.ManyToManyField(related_name='ordered_pizzas', to='webapp.person')),
                ('toppings', models.ManyToManyField(blank=True, related_name='pizzas', to='webapp.topping')),
            ],
        ),
        migrations.CreateModel(
            name='VendorTopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='webapp.topping')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_toppings', to='webapp.pizzavendor')),
            ],
            options={
                'verbose_name_plural': 'Vendor Toppings',
                'unique_together': {('vendor', 'topping')},
            },
        ),
        migrations.AddField(
            model_name='pizzavendor',
            name='toppings',
            field=models.ManyToManyField(related_name='vendors_offering', through='webapp.VendorTopping', to='webapp.topping'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'person')},
        ),
    ]
