# Generated by Django 6.0.2 on 2026-02-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedpizza',
            name='pizza_type',
        ),
        migrations.RemoveField(
            model_name='persontoppingpreference',
            name='weight',
        ),
        migrations.AddField(
            model_name='order',
            name='num_pizzas',
            field=models.IntegerField(default=1, help_text='Number of pizzas to order'),
        ),
        migrations.AddField(
            model_name='order',
            name='optimization_mode',
            field=models.CharField(choices=[('maximize_likes', 'Maximize Likes'), ('minimize_dislikes', 'Minimize Dislikes')], default='maximize_likes', help_text='Which optimization strategy to use', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_mode',
            field=models.CharField(choices=[('whole', 'Whole pizzas only'), ('half', 'Half-and-half allowed')], default='whole', help_text='Whether half-and-half pizzas are allowed', max_length=5),
        ),
        migrations.AddField(
            model_name='persontoppingpreference',
            name='preference',
            field=models.IntegerField(choices=[(-2, 'Allergy'), (-1, 'Dislike'), (0, 'Neutral'), (1, 'Like')], default=0, help_text='Preference level: ALLERGY (-2) is a hard constraint, DISLIKE (-1) is minimized, NEUTRAL (0), LIKE (1) is maximized'),
        ),
    ]
