# Generated by Django 6.0.2 on 2026-02-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_orderedpizza_pizza_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='unrated_is_dislike',
            field=models.BooleanField(default=False, help_text='If True, toppings with no recorded preference are treated as Dislike (-1) during optimization.'),
        ),
    ]
