# Generated by Django 6.0.2 on 2026-02-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_pizzagroup_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzavendor',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Owning group (null = public vendor, visible to everyone)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='webapp.pizzagroup'),
        ),
    ]
