# Generated by Django 6.0.2 on 2026-02-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_person_unrated_is_dislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedpizza',
            name='is_split',
            field=models.BooleanField(default=False),
        ),
    ]
