# Generated by Django 6.0.2 on 2026-02-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_orderedpizza_is_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza_mode',
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='is_split',
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='left_toppings',
        ),
        migrations.RemoveField(
            model_name='orderedpizza',
            name='right_toppings',
        ),
        migrations.AddField(
            model_name='orderedpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='webapp.topping'),
        ),
    ]
