# Generated by Django 6.0.2 on 2026-02-22 03:42

import uuid
from django.db import migrations, models


def populate_guest_tokens(apps, schema_editor):
    Person = apps.get_model('webapp', 'Person')
    for person in Person.objects.all():
        person.guest_token = uuid.uuid4()
        person.save(update_fields=['guest_token'])


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_order_pizza_mode_remove_orderedpizza_is_split_and_more'),
    ]

    operations = [
        # Step 1: add field as nullable with no default so existing rows get NULL
        migrations.AddField(
            model_name='person',
            name='guest_token',
            field=models.UUIDField(null=True, blank=True),
        ),
        # Step 2: populate a unique UUID for every existing row
        migrations.RunPython(populate_guest_tokens, migrations.RunPython.noop),
        # Step 3: make it non-null, unique, and set the model-level default
        migrations.AlterField(
            model_name='person',
            name='guest_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
