# Generated by Django 6.0.2 on 2026-02-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_vendor_to_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauranttopping',
            options={'verbose_name_plural': 'Restaurant Toppings'},
        ),
    ]
