# Generated by Django 6.0.2 on 2026-02-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_restauranttopping_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='optimization_mode',
            field=models.CharField(choices=[('maximize_likes', 'Maximize Likes'), ('minimize_dislikes', 'Minimize Dislikes')], default='minimize_dislikes', help_text='Which optimization strategy to use', max_length=20),
        ),
    ]
