# Generated by Django 6.0.2 on 2026-02-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_change_optimization_mode_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shareability_bonus_weight',
            field=models.FloatField(default=0, help_text="Weight (0–1) applied to non-assigned people's preferences when scoring pizzas. 0 = only assigned people's preferences are considered. Higher values reward pizzas others in the order would also enjoy."),
        ),
    ]
